import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

AMAZON_AFFILIATE_TAG = os.getenv("AMAZON_AFFILIATE_TAG")

WORDPRESS_URL = os.getenv("WORDPRESS_URL")
WORDPRESS_USER = os.getenv("WORDPRESS_USER")
WORDPRESS_APP_PASSWORD = os.getenv("WORDPRESS_APP_PASSWORD")

POST_LIMIT = 100